// Hardcoded karena endpoint API asmaulhusna tidak stabil
const ASMAUL_HUSNA = [
  { no: 1,  nama: "Ar-Rahman",    arab: "ٱلرَّحْمَـٰنُ",        latin: "Ar-Rahmaan",    arti: "Yang Maha Pengasih" },
  { no: 2,  nama: "Ar-Rahim",     arab: "ٱلرَّحِيمُ",           latin: "Ar-Rahiim",     arti: "Yang Maha Penyayang" },
  { no: 3,  nama: "Al-Malik",     arab: "ٱلْمَلِكُ",            latin: "Al-Malik",      arti: "Yang Maha Merajai" },
  { no: 4,  nama: "Al-Quddus",    arab: "ٱلْقُدُّوسُ",          latin: "Al-Qudduus",    arti: "Yang Maha Suci" },
  { no: 5,  nama: "As-Salam",     arab: "ٱلسَّلَامُ",           latin: "As-Salaam",     arti: "Yang Maha Memberi Kesejahteraan" },
  { no: 6,  nama: "Al-Mu'min",    arab: "ٱلْمُؤْمِنُ",          latin: "Al-Mu'min",     arti: "Yang Maha Memberi Keamanan" },
  { no: 7,  nama: "Al-Muhaimin",  arab: "ٱلْمُهَيْمِنُ",        latin: "Al-Muhaimin",   arti: "Yang Maha Memelihara" },
  { no: 8,  nama: "Al-Aziz",      arab: "ٱلْعَزِيزُ",           latin: "Al-'Aziiz",     arti: "Yang Maha Perkasa" },
  { no: 9,  nama: "Al-Jabbar",    arab: "ٱلْجَبَّارُ",          latin: "Al-Jabbaar",    arti: "Yang Maha Memaksa" },
  { no: 10, nama: "Al-Mutakabbir",arab: "ٱلْمُتَكَبِّرُ",       latin: "Al-Mutakabbir", arti: "Yang Maha Megah" },
  { no: 11, nama: "Al-Khaliq",    arab: "ٱلْخَـٰلِقُ",          latin: "Al-Khaaliq",    arti: "Yang Maha Pencipta" },
  { no: 12, nama: "Al-Bari",      arab: "ٱلْبَارِئُ",           latin: "Al-Baari'",     arti: "Yang Maha Mengadakan" },
  { no: 13, nama: "Al-Musawwir",  arab: "ٱلْمُصَوِّرُ",         latin: "Al-Mushawwir",  arti: "Yang Maha Membentuk Rupa" },
  { no: 14, nama: "Al-Ghaffar",   arab: "ٱلْغَفَّارُ",          latin: "Al-Ghaffaar",   arti: "Yang Maha Pengampun" },
  { no: 15, nama: "Al-Qahhar",    arab: "ٱلْقَهَّارُ",          latin: "Al-Qahhaar",    arti: "Yang Maha Perkasa" },
  { no: 16, nama: "Al-Wahhab",    arab: "ٱلْوَهَّابُ",          latin: "Al-Wahhaab",    arti: "Yang Maha Pemberi" },
  { no: 17, nama: "Ar-Razzaq",    arab: "ٱلرَّزَّاقُ",          latin: "Ar-Razzaaq",    arti: "Yang Maha Pemberi Rezeki" },
  { no: 18, nama: "Al-Fattah",    arab: "ٱلْفَتَّاحُ",          latin: "Al-Fattaah",    arti: "Yang Maha Pembuka Rahmat" },
  { no: 19, nama: "Al-'Alim",     arab: "ٱلْعَلِيمُ",           latin: "Al-'Aliim",     arti: "Yang Maha Mengetahui" },
  { no: 20, nama: "Al-Qabidh",    arab: "ٱلْقَابِضُ",           latin: "Al-Qaabidh",    arti: "Yang Maha Menyempitkan" },
  { no: 21, nama: "Al-Basith",    arab: "ٱلْبَاسِطُ",           latin: "Al-Baasith",    arti: "Yang Maha Melapangkan" },
  { no: 22, nama: "Al-Khafidh",   arab: "ٱلْخَافِضُ",           latin: "Al-Khaafidh",   arti: "Yang Maha Merendahkan" },
  { no: 23, nama: "Ar-Rafi",      arab: "ٱلرَّافِعُ",           latin: "Ar-Raafi'",     arti: "Yang Maha Meninggikan" },
  { no: 24, nama: "Al-Mu'izz",    arab: "ٱلْمُعِزُّ",           latin: "Al-Mu'izz",     arti: "Yang Maha Memuliakan" },
  { no: 25, nama: "Al-Mudzill",   arab: "ٱلْمُذِلُّ",           latin: "Al-Mudzill",    arti: "Yang Maha Menghinakan" },
  { no: 26, nama: "As-Sami",      arab: "ٱلسَّمِيعُ",           latin: "As-Samii'",     arti: "Yang Maha Mendengar" },
  { no: 27, nama: "Al-Bashir",    arab: "ٱلْبَصِيرُ",           latin: "Al-Bashiir",    arti: "Yang Maha Melihat" },
  { no: 28, nama: "Al-Hakam",     arab: "ٱلْحَكَمُ",            latin: "Al-Hakam",      arti: "Yang Maha Menetapkan" },
  { no: 29, nama: "Al-'Adl",      arab: "ٱلْعَدْلُ",            latin: "Al-'Adl",       arti: "Yang Maha Adil" },
  { no: 30, nama: "Al-Latif",     arab: "ٱللَّطِيفُ",           latin: "Al-Lathiif",    arti: "Yang Maha Lembut" },
  { no: 31, nama: "Al-Khabir",    arab: "ٱلْخَبِيرُ",           latin: "Al-Khabiir",    arti: "Yang Maha Mengenal" },
  { no: 32, nama: "Al-Halim",     arab: "ٱلْحَلِيمُ",           latin: "Al-Haliim",     arti: "Yang Maha Penyantun" },
  { no: 33, nama: "Al-Azim",      arab: "ٱلْعَظِيمُ",           latin: "Al-'Azhiim",    arti: "Yang Maha Agung" },
  { no: 34, nama: "Al-Ghafur",    arab: "ٱلْغَفُورُ",           latin: "Al-Ghafuur",    arti: "Yang Maha Pengampun" },
  { no: 35, nama: "Asy-Syakur",   arab: "ٱلشَّكُورُ",           latin: "Asy-Syakuur",   arti: "Yang Maha Pembalas Budi" },
  { no: 36, nama: "Al-'Ali",      arab: "ٱلْعَلِيُّ",           latin: "Al-'Aliyy",     arti: "Yang Maha Tinggi" },
  { no: 37, nama: "Al-Kabir",     arab: "ٱلْكَبِيرُ",           latin: "Al-Kabiir",     arti: "Yang Maha Besar" },
  { no: 38, nama: "Al-Hafiz",     arab: "ٱلْحَفِيظُ",           latin: "Al-Hafiizh",    arti: "Yang Maha Memelihara" },
  { no: 39, nama: "Al-Muqit",     arab: "ٱلْمُقِيتُ",           latin: "Al-Muqiit",     arti: "Yang Maha Pemberi Kecukupan" },
  { no: 40, nama: "Al-Hasib",     arab: "ٱلْحَسِيبُ",           latin: "Al-Hasiib",     arti: "Yang Maha Membuat Perhitungan" },
  { no: 41, nama: "Al-Jalil",     arab: "ٱلْجَلِيلُ",           latin: "Al-Jaliil",     arti: "Yang Maha Luhur" },
  { no: 42, nama: "Al-Karim",     arab: "ٱلْكَرِيمُ",           latin: "Al-Kariim",     arti: "Yang Maha Pemurah" },
  { no: 43, nama: "Ar-Raqib",     arab: "ٱلرَّقِيبُ",           latin: "Ar-Raqiib",     arti: "Yang Maha Mengawasi" },
  { no: 44, nama: "Al-Mujib",     arab: "ٱلْمُجِيبُ",           latin: "Al-Mujiib",     arti: "Yang Maha Mengabulkan" },
  { no: 45, nama: "Al-Wasi",      arab: "ٱلْوَٰسِعُ",           latin: "Al-Waasi'",     arti: "Yang Maha Luas" },
  { no: 46, nama: "Al-Hakim",     arab: "ٱلْحَكِيمُ",           latin: "Al-Hakiim",     arti: "Yang Maha Bijaksana" },
  { no: 47, nama: "Al-Wadud",     arab: "ٱلْوَدُودُ",           latin: "Al-Waduud",     arti: "Yang Maha Mencintai" },
  { no: 48, nama: "Al-Majid",     arab: "ٱلْمَجِيدُ",           latin: "Al-Majiid",     arti: "Yang Maha Mulia" },
  { no: 49, nama: "Al-Ba'ith",    arab: "ٱلْبَاعِثُ",           latin: "Al-Baa'its",    arti: "Yang Maha Membangkitkan" },
  { no: 50, nama: "Asy-Syahid",   arab: "ٱلشَّهِيدُ",           latin: "Asy-Syahiid",   arti: "Yang Maha Menyaksikan" },
  { no: 51, nama: "Al-Haqq",      arab: "ٱلْحَقُّ",             latin: "Al-Haqq",       arti: "Yang Maha Benar" },
  { no: 52, nama: "Al-Wakil",     arab: "ٱلْوَكِيلُ",           latin: "Al-Wakiil",     arti: "Yang Maha Memelihara" },
  { no: 53, nama: "Al-Qawi",      arab: "ٱلْقَوِيُّ",           latin: "Al-Qawiyy",     arti: "Yang Maha Kuat" },
  { no: 54, nama: "Al-Matin",     arab: "ٱلْمَتِينُ",           latin: "Al-Matiin",     arti: "Yang Maha Kokoh" },
  { no: 55, nama: "Al-Wali",      arab: "ٱلْوَلِيُّ",           latin: "Al-Waliyy",     arti: "Yang Maha Melindungi" },
  { no: 56, nama: "Al-Hamid",     arab: "ٱلْحَمِيدُ",           latin: "Al-Hamiid",     arti: "Yang Maha Terpuji" },
  { no: 57, nama: "Al-Muhshi",    arab: "ٱلْمُحْصِي",           latin: "Al-Muhshi",     arti: "Yang Maha Menghitung" },
  { no: 58, nama: "Al-Mubdi",     arab: "ٱلْمُبْدِئُ",          latin: "Al-Mubdi'",     arti: "Yang Maha Memulai" },
  { no: 59, nama: "Al-Mu'id",     arab: "ٱلْمُعِيدُ",           latin: "Al-Mu'iid",     arti: "Yang Maha Mengembalikan" },
  { no: 60, nama: "Al-Muhyi",     arab: "ٱلْمُحْيِى",           latin: "Al-Muhyii",     arti: "Yang Maha Menghidupkan" },
  { no: 61, nama: "Al-Mumit",     arab: "ٱلْمُمِيتُ",           latin: "Al-Mumiit",     arti: "Yang Maha Mematikan" },
  { no: 62, nama: "Al-Hayy",      arab: "ٱلْحَيُّ",             latin: "Al-Hayy",       arti: "Yang Maha Hidup" },
  { no: 63, nama: "Al-Qayyum",    arab: "ٱلْقَيُّومُ",          latin: "Al-Qayyuum",    arti: "Yang Maha Mandiri" },
  { no: 64, nama: "Al-Wajid",     arab: "ٱلْوَاجِدُ",           latin: "Al-Waajid",     arti: "Yang Maha Penemu" },
  { no: 65, nama: "Al-Majid",     arab: "ٱلْمَاجِدُ",           latin: "Al-Maajid",     arti: "Yang Maha Mulia" },
  { no: 66, nama: "Al-Wahid",     arab: "ٱلْوَاحِدُ",           latin: "Al-Waahid",     arti: "Yang Maha Tunggal" },
  { no: 67, nama: "Al-Ahad",      arab: "ٱلْأَحَدُ",            latin: "Al-Ahad",       arti: "Yang Maha Esa" },
  { no: 68, nama: "As-Samad",     arab: "ٱلصَّمَدُ",            latin: "As-Shamad",     arti: "Yang Maha Dibutuhkan" },
  { no: 69, nama: "Al-Qadir",     arab: "ٱلْقَادِرُ",           latin: "Al-Qaadir",     arti: "Yang Maha Menentukan" },
  { no: 70, nama: "Al-Muqtadir",  arab: "ٱلْمُقْتَدِرُ",        latin: "Al-Muqtadir",   arti: "Yang Maha Berkuasa" },
  { no: 71, nama: "Al-Muqaddim",  arab: "ٱلْمُقَدِّمُ",         latin: "Al-Muqaddim",   arti: "Yang Maha Mendahulukan" },
  { no: 72, nama: "Al-Muakhkhir", arab: "ٱلْمُؤَخِّرُ",         latin: "Al-Mu'akhkhir", arti: "Yang Maha Mengakhirkan" },
  { no: 73, nama: "Al-Awwal",     arab: "ٱلْأَوَّلُ",           latin: "Al-Awwal",      arti: "Yang Maha Awal" },
  { no: 74, nama: "Al-Akhir",     arab: "ٱلْآخِرُ",             latin: "Al-Aakhir",     arti: "Yang Maha Akhir" },
  { no: 75, nama: "Az-Zahir",     arab: "ٱلظَّاهِرُ",           latin: "Azh-Zhaahir",   arti: "Yang Maha Nyata" },
  { no: 76, nama: "Al-Batin",     arab: "ٱلْبَاطِنُ",           latin: "Al-Baathin",    arti: "Yang Maha Ghaib" },
  { no: 77, nama: "Al-Wali",      arab: "ٱلْوَالِي",            latin: "Al-Waali",      arti: "Yang Maha Memerintah" },
  { no: 78, nama: "Al-Muta'ali",  arab: "ٱلْمُتَعَالِي",        latin: "Al-Muta'aali",  arti: "Yang Maha Tinggi" },
  { no: 79, nama: "Al-Barr",      arab: "ٱلْبَرُّ",             latin: "Al-Barr",       arti: "Yang Maha Dermawan" },
  { no: 80, nama: "At-Tawwab",    arab: "ٱلتَّوَّابُ",          latin: "At-Tawwaab",    arti: "Yang Maha Penerima Tobat" },
  { no: 81, nama: "Al-Muntaqim",  arab: "ٱلْمُنْتَقِمُ",        latin: "Al-Muntaqim",   arti: "Yang Maha Pemberi Azab" },
  { no: 82, nama: "Al-Afuww",     arab: "ٱلْعَفُوُّ",           latin: "Al-'Afuww",     arti: "Yang Maha Pemaaf" },
  { no: 83, nama: "Ar-Ra'uf",     arab: "ٱلرَّءُوفُ",           latin: "Ar-Ra'uuf",     arti: "Yang Maha Pengasuh" },
  { no: 84, nama: "Malikul Mulk", arab: "مَـٰلِكُ ٱلْمُلْكِ",  latin: "Malikul Mulk",  arti: "Yang Maha Penguasa Kerajaan" },
  { no: 85, nama: "Dzul Jalali",  arab: "ذُو ٱلْجَلَـٰلِ وَٱلْإِكْرَامِ", latin: "Dzul Jalaali wal Ikraam", arti: "Yang Maha Pemilik Kebesaran dan Kemuliaan" },
  { no: 86, nama: "Al-Muqsith",   arab: "ٱلْمُقْسِطُ",          latin: "Al-Muqsith",    arti: "Yang Maha Pemberi Keadilan" },
  { no: 87, nama: "Al-Jami",      arab: "ٱلْجَامِعُ",           latin: "Al-Jaami'",     arti: "Yang Maha Mengumpulkan" },
  { no: 88, nama: "Al-Ghani",     arab: "ٱلْغَنِيُّ",           latin: "Al-Ghaniyy",    arti: "Yang Maha Kaya" },
  { no: 89, nama: "Al-Mughni",    arab: "ٱلْمُغْنِي",           latin: "Al-Mughnii",    arti: "Yang Maha Memberi Kekayaan" },
  { no: 90, nama: "Al-Mani",      arab: "ٱلْمَانِعُ",           latin: "Al-Maani'",     arti: "Yang Maha Mencegah" },
  { no: 91, nama: "Ad-Darr",      arab: "ٱلضَّارُّ",            latin: "Ad-Dhaarr",     arti: "Yang Maha Penimpa Kemudharatan" },
  { no: 92, nama: "An-Nafi",      arab: "ٱلنَّافِعُ",           latin: "An-Naafi'",     arti: "Yang Maha Memberi Manfaat" },
  { no: 93, nama: "An-Nur",       arab: "ٱلنُّورُ",             latin: "An-Nuur",       arti: "Yang Maha Bercahaya" },
  { no: 94, nama: "Al-Hadi",      arab: "ٱلْهَادِي",            latin: "Al-Haadii",     arti: "Yang Maha Pemberi Petunjuk" },
  { no: 95, nama: "Al-Badi",      arab: "ٱلْبَدِيعُ",           latin: "Al-Badii'",     arti: "Yang Maha Pencipta Keindahan" },
  { no: 96, nama: "Al-Baqi",      arab: "ٱلْبَاقِي",            latin: "Al-Baaqii",     arti: "Yang Maha Kekal" },
  { no: 97, nama: "Al-Warith",    arab: "ٱلْوَارِثُ",           latin: "Al-Waarits",    arti: "Yang Maha Pewaris" },
  { no: 98, nama: "Ar-Rasyid",    arab: "ٱلرَّشِيدُ",           latin: "Ar-Rasyiid",    arti: "Yang Maha Pandai" },
  { no: 99, nama: "As-Sabur",     arab: "ٱلصَّبُورُ",           latin: "As-Shabuур",    arti: "Yang Maha Sabar" },
];

module.exports = ({ bot }) => {
  bot.command("asmaulhusna", async (ctx) => {
    const item = ASMAUL_HUSNA[Math.floor(Math.random() * ASMAUL_HUSNA.length)];
    return ctx.reply(
      `☪️ *Asmaul Husna*\n\n` +
      `🔢 No. *${item.no}* dari 99\n\n` +
      `📖 *${item.nama}*\n\n` +
      `${item.arab}\n\n` +
      `🔤 _${item.latin}_\n\n` +
      `💡 ${item.arti}`,
      { parse_mode: "Markdown" }
    );
  });
};
